from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SapFlower(object):
    def setupUi(self, SapFlower):
        SapFlower.setObjectName("SapFlower")
        SapFlower.resize(1221, 810)
        SapFlower.setWindowIcon(QtGui.QIcon("SapFlower_white_bg.ico"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(SapFlower.sizePolicy().hasHeightForWidth())
        SapFlower.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        SapFlower.setFont(font)
        SapFlower.setStyleSheet("font: 8pt \"Arial\";\n"
"background: rgb(13,110,117)")
        self.centralwidget = QtWidgets.QWidget(SapFlower)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_2.setStyleSheet("")
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.verticalWidget_2)
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 147))
        self.graphicsView.setStyleSheet("background:rgb(170, 85, 0)")
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()  # Change this variable name to avoid conflict
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Deletedata = QtWidgets.QPushButton(self.verticalWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Deletedata.setFont(font)
        self.Deletedata.setStyleSheet("background-color: rgb(193,113,77);")
        self.Deletedata.setObjectName("Deletedata")
        self.horizontalLayout_3.addWidget(self.Deletedata)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalWidget_2)
        self.pushButton_2.setStyleSheet("background-color: rgb(18,201,122);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalWidget_2)
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.verticalWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.verticalWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_7.setClearButtonEnabled(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout.addWidget(self.lineEdit_7)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.verticalWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_9.setClearButtonEnabled(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout.addWidget(self.lineEdit_9)
        self.checkBox = QtWidgets.QCheckBox(self.verticalWidget_2)
        self.checkBox.setStyleSheet("color : rgb(255, 255, 255)")
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalWidget_2)
        self.checkBox_2.setStyleSheet("color : rgb(255, 255, 255)")
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.progressBar = QtWidgets.QProgressBar(self.verticalWidget_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.verticalWidget_2)
        self.plainTextEdit.setAutoFillBackground(False)
        self.plainTextEdit.setStyleSheet("background-color: rgb(30, 30, 30); color: white\n"
"\n"
"")
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.verticalWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(214, 214, 214);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.label_9 = QtWidgets.QLabel(self.verticalWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgba(255,0,0,160);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout.addWidget(self.verticalWidget_2, 0, 0, 1, 1)
        SapFlower.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SapFlower)
        self.statusbar.setObjectName("statusbar")
        SapFlower.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(SapFlower)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1221, 22))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTraining = QtWidgets.QMenu(self.menubar)
        self.menuTraining.setObjectName("menuTraining")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuCalculate = QtWidgets.QMenu(self.menubar)
        self.menuCalculate.setObjectName("menuCalculate")
        self.menuGapfill = QtWidgets.QMenu(self.menubar)
        self.menuGapfill.setObjectName("menuGapfill")
        self.menuHelp_2 = QtWidgets.QMenu(self.menubar)
        self.menuHelp_2.setObjectName("menuHelp_2")
        self.menuPlot = QtWidgets.QMenu(self.menubar)
        self.menuPlot.setObjectName("menuPlot")
        SapFlower.setMenuBar(self.menubar)
        self.actionH = QtWidgets.QAction(SapFlower)
        self.actionH.setObjectName("actionH")
        self.action = QtWidgets.QAction(SapFlower)
        self.action.setObjectName("action")
        self.actionYOLOv8_seg_x = QtWidgets.QAction(SapFlower)
        self.actionYOLOv8_seg_x.setObjectName("actionYOLOv8_seg_x")
        self.actionGoogle_scholar = QtWidgets.QAction(SapFlower)
        self.actionGoogle_scholar.setObjectName("actionGoogle_scholar")
        self.actionarXiv = QtWidgets.QAction(SapFlower)
        self.actionarXiv.setObjectName("actionarXiv")
        self.actionGitHub = QtWidgets.QAction(SapFlower)
        self.actionGitHub.setObjectName("actionGitHub")
        self.actionMy_Homepage = QtWidgets.QAction(SapFlower)
        self.actionMy_Homepage.setObjectName("actionMy_Homepage")
        self.actionEarly_versions = QtWidgets.QAction(SapFlower)
        self.actionEarly_versions.setObjectName("actionEarly_versions")
        self.actionOnly_whole_stomata = QtWidgets.QAction(SapFlower)
        self.actionOnly_whole_stomata.setCheckable(True)
        self.actionOnly_whole_stomata.setObjectName("actionOnly_whole_stomata")
        self.actionOnly_stomata_aperture = QtWidgets.QAction(SapFlower)
        self.actionOnly_stomata_aperture.setCheckable(True)
        self.actionOnly_stomata_aperture.setObjectName("actionOnly_stomata_aperture")
        self.actionOnly_guard_cell = QtWidgets.QAction(SapFlower)
        self.actionOnly_guard_cell.setCheckable(True)
        self.actionOnly_guard_cell.setObjectName("actionOnly_guard_cell")
        self.actionAll_metrics = QtWidgets.QAction(SapFlower)
        self.actionAll_metrics.setCheckable(True)
        self.actionAll_metrics.setChecked(True)
        self.actionAll_metrics.setObjectName("actionAll_metrics")
        self.actionGroup_Analysis = QtWidgets.QAction(SapFlower)
        self.actionGroup_Analysis.setObjectName("actionGroup_Analysis")
        self.actionOpen_training_window = QtWidgets.QAction(SapFlower)
        self.actionOpen_training_window.setObjectName("actionOpen_training_window")
        self.menuHelp.addAction(self.actionMy_Homepage)
        self.menuTraining.addAction(self.actionOpen_training_window)
        self.menubar.addAction(self.menuTraining.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuCalculate.menuAction())
        self.menubar.addAction(self.menuGapfill.menuAction())
        self.menubar.addAction(self.menuPlot.menuAction())
        self.menubar.addAction(self.menuHelp_2.menuAction())

        self.retranslateUi(SapFlower)
        QtCore.QMetaObject.connectSlotsByName(SapFlower)

    def retranslateUi(self, SapFlower):
        _translate = QtCore.QCoreApplication.translate
        SapFlower.setWindowTitle(_translate("SapFlower", "SapFlower1"))
        self.Deletedata.setText(_translate("SapFlower", "Delete selected data"))
        self.pushButton_2.setText(_translate("SapFlower", "Undo deletion"))
        self.pushButton_4.setText(_translate("SapFlower", "Invert selected data"))
        self.pushButton_6.setText(_translate("SapFlower", "Undo inversion"))
        self.pushButton_7.setText(_translate("SapFlower", "Save data"))
        self.lineEdit_7.setText(_translate("SapFlower", "Fliplr, default is 0.0"))
        self.lineEdit_9.setText(_translate("SapFlower", "Workers, default is 0"))
        self.checkBox.setText(_translate("SapFlower", "AMP Check, uncheck it if you got nan for training"))
        self.checkBox_2.setText(_translate("SapFlower", "Train on CPU"))
        self.label_3.setText(_translate("SapFlower", "© Jiaxin Wang.  For questions or requests 📧  coolwjx@foxmail.com; jw3994@msstate.edu"))
        self.label_9.setText(_translate("SapFlower", "💕   LU"))
        self.menuHelp.setTitle(_translate("SapFlower", "Edit"))
        self.menuTraining.setTitle(_translate("SapFlower", "File"))
        self.menuView.setTitle(_translate("SapFlower", "View"))
        self.menuCalculate.setTitle(_translate("SapFlower", "Calculate"))
        self.menuGapfill.setTitle(_translate("SapFlower", "Gapfill"))
        self.menuHelp_2.setTitle(_translate("SapFlower", "Help"))
        self.menuPlot.setTitle(_translate("SapFlower", "Plot"))
        self.actionH.setText(_translate("SapFlower", "H"))
        self.action.setText(_translate("SapFlower", ")"))
        self.actionYOLOv8_seg_x.setText(_translate("SapFlower", "YOLOv8-seg-x"))
        self.actionGoogle_scholar.setText(_translate("SapFlower", "Google scholar"))
        self.actionarXiv.setText(_translate("SapFlower", "arXiv"))
        self.actionGitHub.setText(_translate("SapFlower", "GitHub"))
        self.actionMy_Homepage.setText(_translate("SapFlower", "Ultralytics"))
        self.actionEarly_versions.setText(_translate("SapFlower", "Early versions"))
        self.actionOnly_whole_stomata.setText(_translate("SapFlower", "Only whole_stomata"))
        self.actionOnly_stomata_aperture.setText(_translate("SapFlower", "Only stomata (aperture)"))
        self.actionOnly_guard_cell.setText(_translate("SapFlower", "Only guard cell"))
        self.actionAll_metrics.setText(_translate("SapFlower", "All metrics"))
        self.actionGroup_Analysis.setText(_translate("SapFlower", "Group Analysis"))
        self.actionOpen_training_window.setText(_translate("SapFlower", "Train YOLOv8-seg-x"))
